apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  namespace: fzyun-aione
spec:
  storageClassName: fzyun-aione
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
